sudo: required
services:
- docker

before_install:
- docker pull dpollet/texlive:pillar

script: |
  docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar bash -c "\
    wget --quiet --output-document=- 'https://raw.githubusercontent.com/pillar-markup/pillar/master/download.sh' | bash \
    && make spiralbook "

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/MasteringMoose
  skip_cleanup: true
  user: ducasse
  key:
    secure: qELwtWWS9l/5fS/6vXDAHqLX5cWncg1aOun/W4Sk09VVDk2VAyiBBVyx1FPZV7Ij3lvojxBzxx1a4MlCB78zHx1kYYYPaPZ7PQiafX6Vm+V5a16Qz285zHfijlC60Ev2681QXhkbpB9j4IJPHAR9ZAi2IfrJJfqAbPPqUte0qGG2liQenTjCA+z4wbVN6e5xrEoiXMDDoYqo6gVpo43dRvTebpFeAkGpK/fCahud2/QB11VZg9Q9mOtPKxuqyZiMZ/PTgMj2729oPqilEW1IIZOjJE02Qxlt8ONy3jKkgHD9P9J6VQCyAPIB8xN2LbEqOwn54WcBUWHhQbFYjQPFMjgPODx2a5BVFv4TCsaFD97Oa+LNtsZIx/ZPBaajBbSiFmY4YEGrpj6+OyAktQ/OvoZPFhYVJGuDhCDvJDWuJekJtUIuBKwicRTbvsQmw43o6eTlqTMdMtJ2ineRWfYOMesXP+QC5GNHoshalZuvwHLC9cgD4Dw2csbbTYZSeitQ3tAJ3kVqZURZiWDOTtwTmP0u5fbBr5+6yNbtbOzTfg9Yr6bWoDuurzeaEBWnGP4i8Ku3VKi6fvgnpFMos9KD4FT+E2Ve2vgOXPw7iHogL9PT5ENZnC2pYfnqwGygaNT3Vdk6FpJeVV3BE3eikmLkW02Mp6QHl0j+ZIK/e2rtgWk=
- provider: releases
  file: build/books.spiral.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
